name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container Security scan on a container image"

inputs:
  endpoint:
    description: "AccuKnox endpoint URL"
    required: true
  token:
    description: "Token to authenticate with AccuKnox"
    required: true
  label:
    description: "Label to tag scan results in AccuKnox"
    required: true
  image:
    description: "Name of the container image to scan"
    required: true
  soft_fail:
    description: "Do not fail workflow if vulnerabilities are found"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        LABEL: ${{ inputs.label }}
        IMAGE: ${{ inputs.image }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$LABEL" ] || [ -z "$IMAGE" ]; then
          echo "ERROR: endpoint, token, label, and image must be provided!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        CMD_ARGS="--image $IMAGE"

        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        echo "Running AccuKnox container scan with CMD_ARGS: $CMD_ARGS $SOFT_FAIL_ARG"
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command "$CMD_ARGS"
