name: "AccuKnox Container Scan"
description: "Run AccuKnox container image scan and optional SBOM generation"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    required: true
  accuknox_label:
    required: true
  accuknox_endpoint:
    required: true
  image_name:
    required: true
  tag:
    required: false
    default: ""
  severity:
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  soft_fail:
    required: false
    default: false
  generate_sbom:
    required: false
    default: false
  project_name:
    required: false
    default: ""
  keep_results:
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------------------
    # SETUP (COMMON)
    # ---------------------------------------------------------
    - name: Setup AccuKnox Scanner
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        # ---- Mandatory validation ----
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: Required inputs missing"
          exit 1
        fi

        GENERATE_SBOM="${GENERATE_SBOM,,}"
        GENERATE_SBOM="${GENERATE_SBOM//[$'\t\r\n ']}"

        if [ "$GENERATE_SBOM" = "true" ] && [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "ERROR: project_name is required when generate_sbom is true"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -sSL https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

    # ---------------------------------------------------------
    # CONTAINER IMAGE SCAN (ALWAYS RUNS)
    # ---------------------------------------------------------
    - name: Run AccuKnox Container Image Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e

        SOFT_FAIL="${SOFT_FAIL,,}"
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"

        SOFT_FAIL_ARG=""
        [ "$SOFT_FAIL" = "true" ] && SOFT_FAIL_ARG="--softfail"

        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
        [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"

        echo "Running AccuKnox container image scan..."
        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          container \
          --command "$CMD" \
          --container-mode

    # ---------------------------------------------------------
    # SBOM GENERATION (OPTIONAL)
    # ---------------------------------------------------------
    - name: Run SBOM Generation Scan
      if: ${{ inputs.generate_sbom == 'true' }}
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        KEEP_RESULTS="${KEEP_RESULTS,,}"
        KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"

        KEEP_RESULTS_ARG=""
        [ "$KEEP_RESULTS" = "true" ] && KEEP_RESULTS_ARG="--keep-results"

        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"

        echo "Running SBOM generation scan..."
        ./accuknox-aspm-scanner scan \
          $KEEP_RESULTS_ARG \
          --project-name "$ACCUKNOX_PROJECT_NAME" \
          container \
          --command "$CMD" \
          --container-mode \
          --generate-sbom
