name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container Security scan on the current repository's container image"

inputs:
  token:
    description: "API token for CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
  severity:
    description: "Optional severity filter (e.g., HIGH, CRITICAL)"
    required: false
    default: ""
  soft_fail:
    description: "Continue workflow even if vulnerabilities are found"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        REPO_NAME: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ]; then
          echo "ERROR: token, label, and endpoint must be provided!"
          exit 1
        fi

        IMAGE_NAME="$REPO_NAME"
        IMAGE_TAG="$RUN_ID"

        echo "Building Docker image from current repository: $IMAGE_NAME:$IMAGE_TAG"
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        # Build severity argument
        SEVERITY_ARG=""
        [ -n "$SEVERITY" ] && SEVERITY_ARG="--severity $SEVERITY"

        # Build softfail argument
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        echo "Running AccuKnox container scan for image: $IMAGE_NAME:$IMAGE_TAG"
        ./accuknox-aspm-scanner scan --command container --image "$IMAGE_NAME:$IMAGE_TAG" $SEVERITY_ARG $SOFT_FAIL_ARG --container-mode
