name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container Security scan on a container image"

inputs:
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
  token:
    description: "API token for CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  image_name:
    description: "Container image to scan (e.g., nginx)"
    required: true
  tag:
    description: "Optional tag for the image (e.g., latest)"
    required: false
  severity:
    description: "Optional severity filter (e.g., high, critical)"
    required: false
  soft_fail:
    description: "Continue workflow even if vulnerabilities are found"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scan
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: endpoint, token, label, and image_name must be provided!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        # Build scan command
        SOFT_FAIL_ARG=""
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        CMD="$IMAGE_NAME"
        [ -n "$TAG" ] && CMD="$CMD:$TAG"
        [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"

        echo "Running AccuKnox container scan for image: $CMD"
        ./accuknox-aspm-scanner scan --command container --image "$CMD" $SOFT_FAIL_ARG --container-mode
