name: "AccuKnox Container Scan"
description: "Run AccuKnox container image vulnerability scan and optional SBOM generation"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    required: true
  accuknox_label:
    required: true
  accuknox_endpoint:
    required: true
  image_name:
    required: true
  tag:
    required: false
    default: ""
  severity:
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  soft_fail:
    required: false
    default: false
  generate_sbom:
    required: false
    default: false
  project_name:
    required: false
    default: ""
  keep_results:
    required: false
    default: false

runs:
  using: "composite"
  steps:

    # -----------------------------
    # SETUP (COMMON, RUNS ONCE)
    # -----------------------------
    - name: Setup AccuKnox Scanner
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        # ---- Mandatory checks ----
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || \
           [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: Required inputs missing"
          exit 1
        fi

        # ---- Normalize flags ----
        normalize() {
          echo "${1,,}" | tr -d '[:space:]'
        }

        GENERATE_SBOM="$(normalize "$GENERATE_SBOM")"
        SOFT_FAIL="$(normalize "$SOFT_FAIL")"
        KEEP_RESULTS="$(normalize "$KEEP_RESULTS")"

        if [ "$GENERATE_SBOM" = "true" ] && [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "ERROR: project_name is required when generate_sbom is true"
          exit 1
        fi

        # ---- Download scanner once ----
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -sSL https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner \
          -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        # ---- Build image command ----
        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
        [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"

        echo "CMD=$CMD" >> $GITHUB_ENV

        # ---- Optional args ----
        [ "$SOFT_FAIL" = "true" ] && echo "SOFT_FAIL_ARG=--softfail" >> $GITHUB_ENV || echo "SOFT_FAIL_ARG=" >> $GITHUB_ENV
        [ "$KEEP_RESULTS" = "true" ] && echo "KEEP_RESULTS_ARG=--keep-results" >> $GITHUB_ENV || echo "KEEP_RESULTS_ARG=" >> $GITHUB_ENV

    # -----------------------------
    # SBOM GENERATION (OPTIONAL)
    # -----------------------------
    - name: Run SBOM Generation Scan
      if: ${{ inputs.generate_sbom == 'true' }}
      shell: bash
      env:
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        set -e
        echo "Running SBOM generation scan..."

        ./accuknox-aspm-scanner scan \
          $KEEP_RESULTS_ARG \
          --project-name "$ACCUKNOX_PROJECT_NAME" \
          container \
          --command "$CMD" \
          --container-mode \
          --generate-sbom

    # -----------------------------
    # CONTAINER IMAGE SCAN (ALWAYS)
    # -----------------------------
    - name: Run AccuKnox Container Image Scan
      shell: bash
      run: |
        set -e
        echo "Running AccuKnox container image scan..."

        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          container \
          --command "$CMD" \
          --container-mode
