name: "AccuKnox Container Scan"
description: "Run AccuKnox container vulnerability scan or SBOM generation"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    required: true
  accuknox_label:
    required: true
  accuknox_endpoint:
    required: true
  image_name:
    required: true
  tag:
    required: false
    default: ""
  severity:
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  soft_fail:
    required: false
    default: false
  generate_sbom:
    required: false
    default: false
  project_name:
    required: false
    default: ""
  keep_results:
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # SETUP (COMMON)
    - name: Setup AccuKnox Scanner
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: Required inputs missing"
          exit 1
        fi

        GENERATE_SBOM="${GENERATE_SBOM,,}"
        GENERATE_SBOM="${GENERATE_SBOM//[$'\t\r\n ']}"

        if [ "$GENERATE_SBOM" = "true" ] && [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "ERROR: project_name is required when generate_sbom is true"
          exit 1
        fi

        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        ./accuknox-aspm-scanner tool install --type container

        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"

        echo "CMD=$CMD" >> $GITHUB_ENV

        SOFT_FAIL="${SOFT_FAIL,,}"
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"

        [ "$SOFT_FAIL" = "true" ] && echo "SOFT_FAIL_ARG=--softfail" >> $GITHUB_ENV || echo "SOFT_FAIL_ARG=" >> $GITHUB_ENV

        KEEP_RESULTS="${KEEP_RESULTS,,}"
        KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"

        [ "$KEEP_RESULTS" = "true" ] && echo "KEEP_RESULTS_ARG=--keep-results" >> $GITHUB_ENV || echo "KEEP_RESULTS_ARG=" >> $GITHUB_ENV

    - name: Run SBOM generation scan
      if: ${{ inputs.generate_sbom == 'true' }}
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e
    
        if [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "ERROR: project_name is mandatory for SBOM generation"
          exit 1
        fi
    
        KEEP_RESULTS="${KEEP_RESULTS,,}"
        KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"
        KEEP_RESULTS_ARG=""
        [ "$KEEP_RESULTS" = "true" ] && KEEP_RESULTS_ARG="--keep-results"
    
        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
    
        echo "Running SBOM generation scan for project: $ACCUKNOX_PROJECT_NAME"
    
        ./accuknox-aspm-scanner scan \
          container \
          --command "$CMD" \
          --container-mode \
          --generate-sbom \
          --project-name "$ACCUKNOX_PROJECT_NAME" \
          $KEEP_RESULTS_ARG

    # VULNERABILITY SCAN (DEFAULT)

    - name: Run AccuKnox Container Image Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e
    
        # ---- Mandatory checks ----
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: token, label, endpoint, and image_name must be provided!"
          exit 1
        fi
    
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -sSL https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner
    
        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container
    
        # ---- Soft fail handling ----
        SOFT_FAIL="${SOFT_FAIL,,}"
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
    
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi
    
        # ---- Build image command ----
        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
        [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"
    
        echo "Running AccuKnox container image scan..."
        echo "./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command \"$CMD\" --container-mode"
    
        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          container \
          --command "$CMD" \
          --container-mode
