name: "AccuKnox Container Scan"
description: "Run AccuKnox container vulnerability scan and/or SBOM generation"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    required: true
  accuknox_label:
    required: true
  accuknox_endpoint:
    required: true

  image_name:
    required: true
  tag:
    required: false
    default: ""

  severity:
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

  soft_fail:
    required: false
    default: false

  generate_sbom:
    required: false
    default: false

  project_name:
    required: false
    default: ""

  keep_results:
    required: false
    default: false

runs:
  using: "composite"
  steps:

    # ----------------------------------------------------
    # SETUP (COMMON)
    # ----------------------------------------------------
    - name: Setup AccuKnox Scanner
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        # ---- Mandatory checks ----
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "❌ Required inputs missing"
          exit 1
        fi

        # ---- Normalize booleans ----
        SOFT_FAIL="${SOFT_FAIL,,}"
        GENERATE_SBOM="${GENERATE_SBOM,,}"
        KEEP_RESULTS="${KEEP_RESULTS,,}"

        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        GENERATE_SBOM="${GENERATE_SBOM//[$'\t\r\n ']}"
        KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"

        if [ "$GENERATE_SBOM" = "true" ] && [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "❌ project_name is required when generate_sbom=true"
          exit 1
        fi

        # ---- Download scanner ----
        curl -sSL https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        ./accuknox-aspm-scanner tool install --type container

        # ---- Build command ----
        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"

        echo "CMD=$CMD" >> "$GITHUB_ENV"

        # ---- Persist flags ----
        [ "$SOFT_FAIL" = "true" ] && echo "SOFT_FAIL_ARG=--softfail" >> "$GITHUB_ENV" || echo "SOFT_FAIL_ARG=" >> "$GITHUB_ENV"
        [ "$KEEP_RESULTS" = "true" ] && echo "KEEP_RESULTS_ARG=--keep-results" >> "$GITHUB_ENV" || echo "KEEP_RESULTS_ARG=" >> "$GITHUB_ENV"

    # ----------------------------------------------------
    # SBOM GENERATION
    # ----------------------------------------------------
    - name: Run SBOM generation scan
      if: ${{ inputs.generate_sbom == 'true' }}
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        set -e
        echo "🧾 Running SBOM scan..."

        ./accuknox-aspm-scanner scan \
          container \
          --command "$CMD" \
          --container-mode \
          --generate-sbom \
          --project-name "$ACCUKNOX_PROJECT_NAME" \
          $KEEP_RESULTS_ARG

    # ----------------------------------------------------
    # VULNERABILITY SCAN
    # ----------------------------------------------------
    - name: Run AccuKnox Container Vulnerability Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        SEVERITY: ${{ inputs.severity }}
      run: |
        set -e
        echo "🔍 Running vulnerability scan..."

        FINAL_CMD="$CMD"
        [ -n "$SEVERITY" ] && FINAL_CMD="$FINAL_CMD --severity $SEVERITY"

        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          container \
          --command "$FINAL_CMD" \
          --container-mode \
          $KEEP_RESULTS_ARG
