name: "AccuKnox Container Scan"
description: "Run AccuKnox container vulnerability scan and optionally generate SBOM"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    description: "Token for authenticating with AccuKnox CSPM"
    required: true
  accuknox_label:
    description: "Label created in AccuKnox SaaS"
    required: true
  accuknox_endpoint:
    description: "AccuKnox CSPM endpoint URL"
    required: true
  image_name:
    description: "Docker image name to scan"
    required: true
  tag:
    description: "Docker image tag"
    required: false
    default: ""
  severity:
    description: "Comma-separated severities for vulnerability gating"
    required: false
    default: ""
  soft_fail:
    description: "Do not fail pipeline on vulnerability findings"
    required: false
    default: false
  generate_sbom:
    description: "Generate SBOM in addition to vulnerability scan"
    required: false
    default: false
  project_name:
    description: "AccuKnox project name (required when generate_sbom=true)"
    required: false
    default: ""
  keep_results:
    description: "Keep scan result files"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scanner
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        # Basic validation
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: accuknox_token, accuknox_label, accuknox_endpoint, and image_name are required"
          exit 1
        fi

        # Normalize booleans
        GENERATE_SBOM="${GENERATE_SBOM,,}"; GENERATE_SBOM="${GENERATE_SBOM//[$'\t\r\n ']}"
        SOFT_FAIL="${SOFT_FAIL,,}"; SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        KEEP_RESULTS="${KEEP_RESULTS,,}"; KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"

        # Validate SBOM requirements
        if [ "$GENERATE_SBOM" = "true" ] && [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
          echo "ERROR: project_name is required when generate_sbom=true"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -fsSL https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        # Build base image command
        BASE_CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && BASE_CMD="image $IMAGE_NAME:$TAG"

        # Optional flags
        SOFT_FAIL_ARG=""; [ "$SOFT_FAIL" = "true" ] && SOFT_FAIL_ARG="--softfail"
        KEEP_RESULTS_ARG=""; [ "$KEEP_RESULTS" = "true" ] && KEEP_RESULTS_ARG="--keep-results"

        # ---------------- SBOM SCAN (optional) ----------------
        if [ "$GENERATE_SBOM" = "true" ]; then
          echo "Running SBOM generation scan..."
          ./accuknox-aspm-scanner scan \
            container \
            --command "$BASE_CMD" \
            --container-mode \
            --generate-sbom \
            --project-name "$ACCUKNOX_PROJECT_NAME"
        fi

        # ---------------- VULNERABILITY SCAN (always runs) ----------------
        VULN_CMD="$BASE_CMD"
        [ -n "$SEVERITY" ] && VULN_CMD="$VULN_CMD --severity $SEVERITY"

        echo "Running container vulnerability scan..."
        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          $KEEP_RESULTS_ARG \
          container \
          --command "$VULN_CMD" \
          --container-mode
