name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container Security scan on a container image"

inputs:
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
  token:
    description: "API token for CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  image:
    description: "Container image to scan (e.g., nginx)"
    required: true
  soft_fail:
    description: "Continue workflow even if vulnerabilities are found"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scan
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        IMAGE: ${{ inputs.image }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
      set -e
      if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$IMAGE" ]; then
        echo "ERROR: endpoint, token, label, and image must be provided!"
        exit 1
      fi
      
      echo "Downloading AccuKnox ASPM Scanner..."
      curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
      chmod +x accuknox-aspm-scanner
      
      echo "Installing container scan tool..."
      ./accuknox-aspm-scanner tool install --type container
      
      # Build scan command
      SCAN_CMD="./accuknox-aspm-scanner scan --command container --image $IMAGE"
      [ "$SOFT_FAIL" = "true" ] && SCAN_CMD="$SCAN_CMD --softfail"
      
      echo "Running AccuKnox container scan for image: $IMAGE"
      eval $SCAN_CMD
