name: "AccuKnox Container Scan"
description: "Run AccuKnox Container Security scan and optional SBOM generation"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    required: true
  accuknox_label:
    required: true
  accuknox_endpoint:
    required: true
  image_name:
    required: true
  tag:
    required: false
    default: ""
  severity:
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  soft_fail:
    required: false
    default: false
  generate_sbom:
    required: false
    default: false
  project_name:
    required: false
    default: ""
  keep_results:
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        GENERATE_SBOM: ${{ inputs.generate_sbom }}
        ACCUKNOX_PROJECT_NAME: ${{ inputs.project_name }}
        KEEP_RESULTS: ${{ inputs.keep_results }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || \
           [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: Required inputs missing"
          exit 1
        fi

        # Normalize flags
        GENERATE_SBOM="${GENERATE_SBOM,,}"
        GENERATE_SBOM="${GENERATE_SBOM//[$'\t\r\n ']}"

        SOFT_FAIL="${SOFT_FAIL,,}"
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"

        KEEP_RESULTS="${KEEP_RESULTS,,}"
        KEEP_RESULTS="${KEEP_RESULTS//[$'\t\r\n ']}"

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"

        SOFT_FAIL_ARG=""
        [ "$SOFT_FAIL" = "true" ] && SOFT_FAIL_ARG="--softfail"

        KEEP_RESULTS_ARG=""
        [ "$KEEP_RESULTS" = "true" ] && KEEP_RESULTS_ARG="--keep-results"

        # -------------------------------
        # SBOM SCAN (UNCHANGED COMMAND)
        # -------------------------------
        if [ "$GENERATE_SBOM" = "true" ]; then
          if [ -z "$ACCUKNOX_PROJECT_NAME" ]; then
            echo "ERROR: project_name is required when generate_sbom is true!"
            exit 1
          fi

          echo "Running SBOM generation scan..."

          ./accuknox-aspm-scanner scan \
            $KEEP_RESULTS_ARG \
            --project-name "$ACCUKNOX_PROJECT_NAME" \
            container \
            --command "$CMD" \
            --container-mode \
            --generate-sbom
        fi

        # -------------------------------
        # CONTAINER VULN SCAN (UNCHANGED)
        # -------------------------------
        echo "Running container vulnerability scan..."

        ./accuknox-aspm-scanner scan \
          $SOFT_FAIL_ARG \
          container \
          --command "$CMD --severity $SEVERITY" \
          --container-mode
