name: "AccuKnox Container Scanner"
description: "Run AccuKnox container image scan"

inputs:
  image:
    description: "Container image to scan (e.g., nginx:latest)"
    required: true
  soft_fail:
    description: "Do not return an error code if there are failed checks"
    required: false
    default: false
  endpoint:
    description: "CSPM panel endpoint URL"
    required: true
  label:
    description: "Label in AccuKnox SaaS for scan results"
    required: true
  token:
    description: "Token for authenticating with CSPM panel"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        IMAGE: ${{ inputs.image }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_TOKEN" ]; then
          echo "ERROR: ACCUKNOX_ENDPOINT, ACCUKNOX_LABEL, and ACCUKNOX_TOKEN must be set!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        CMD_ARGS="--image $IMAGE"

        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        echo ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command "$CMD_ARGS" \
          --repo-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" \
          --repo-branch "${GITHUB_REF#refs/heads/}"

        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command "$CMD_ARGS" \
          --repo-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" \
          --repo-branch "${GITHUB_REF#refs/heads/}"
